# Generated by Django 5.2.12 on 2026-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_job_department_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_mode',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], db_index=True, default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='careers/logos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Markdown eligibility for external listings'),
        ),
        migrations.AddField(
            model_name='job',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.TextField(blank=True, help_text="Comma-separated tags, e.g. 'Python, Django, Remote'"),
        ),
    ]
