# Generated by Django 5.2.15 on 2026-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_job_apply_mode_job_company_logo_job_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags_text',
            field=models.TextField(blank=True, help_text="Comma-separated tags, e.g. 'Python, Django, Remote'"),
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
