# Generated by Django 5.2.15 on 2026-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_job_tags_text_remove_job_tags'),
        ('courses', '0007_tag_delete_skill_certificate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='courses.tag'),
        ),
    ]
