# Generated by Django 5.2.12 on 2026-04-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, help_text='Optional link when banner is clicked')),
                ('bg_color', models.CharField(default='#00D4FF', help_text='Hex color, e.g. #00D4FF', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
