# Generated by Django 5.2.12 on 2026-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('hero', 'Hero (default branding)'), ('course', 'Course'), ('event', 'Event'), ('program', 'Program')], max_length=20)),
                ('item_slug', models.SlugField(blank=True, help_text='Slug of the course/event/program. Leave blank for hero slides.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Show maintenance page to all visitors')),
                ('maintenance_message', models.CharField(blank=True, default="We'll be back shortly.", max_length=500)),
                ('course_enrollment_enabled', models.BooleanField(default=True, help_text='Allow students to enroll in courses')),
                ('event_registration_enabled', models.BooleanField(default=True, help_text='Allow users to register for events')),
                ('program_registration_enabled', models.BooleanField(default=True, help_text='Allow users to register for programs')),
                ('auto_publish_student_projects', models.BooleanField(default=True, help_text='Auto-publish student-submitted projects (False = admin approval required)')),
                ('search_results_per_category', models.PositiveIntegerField(default=5, help_text='Max results per category in global search')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
