# Generated by Django 5.2.12 on 2026-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_carouselslide_platformsettings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carouselslide',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_carousel_order'),
        ),
        migrations.AddConstraint(
            model_name='carouselslide',
            constraint=models.UniqueConstraint(condition=models.Q(('item_slug', ''), _negated=True), fields=('slide_type', 'item_slug'), name='unique_carousel_item'),
        ),
    ]
