# Generated by Django 5.2.15 on 2026-06-22 14:03

from django.db import migrations, models


def migrate_to_site_config(apps, schema_editor):
    PlatformSettings = apps.get_model('common', 'PlatformSettings')
    SiteBanner = apps.get_model('common', 'SiteBanner')
    CarouselSlide = apps.get_model('common', 'CarouselSlide')
    GalleryImage = apps.get_model('common', 'GalleryImage')
    SiteConfig = apps.get_model('common', 'SiteConfig')

    # Get or create the single SiteConfig row
    config, created = SiteConfig.objects.get_or_create(id=1)

    settings = PlatformSettings.objects.first()
    if settings:
        config.maintenance_mode = settings.maintenance_mode
        config.maintenance_message = settings.maintenance_message
        config.course_enrollment_enabled = settings.course_enrollment_enabled
        config.event_registration_enabled = settings.event_registration_enabled
        config.program_registration_enabled = settings.program_registration_enabled
        config.auto_publish_student_projects = settings.auto_publish_student_projects
        config.search_results_per_category = settings.search_results_per_category

    banner = SiteBanner.objects.first()
    if banner:
        config.banner_text = banner.text
        config.banner_link = banner.link
        config.banner_bg_color = banner.bg_color
        config.banner_text_color = banner.text_color
        config.banner_is_active = banner.is_active

    # Migrate CarouselSlide
    slides_list = []
    for slide in CarouselSlide.objects.all():
        slides_list.append({
            "slide_type": slide.slide_type,
            "item_slug": slide.item_slug,
            "order": slide.order,
            "is_active": slide.is_active
        })
    config.carousel_slides = slides_list

    # Migrate GalleryImage
    images_list = []
    for img in GalleryImage.objects.all():
        images_list.append({
            "title": img.title,
            "image": img.image.name if img.image else "",
            "caption": img.caption,
            "order": img.order,
            "is_active": img.is_active,
            "is_featured": img.is_featured
        })
    config.gallery_images = images_list

    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_galleryimage_generalfaq'),
        ('courses', '0008_alter_coursereview_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Show maintenance page to all visitors')),
                ('maintenance_message', models.CharField(blank=True, default="We'll be back shortly.", max_length=500)),
                ('course_enrollment_enabled', models.BooleanField(default=True, help_text='Allow students to enroll in courses')),
                ('event_registration_enabled', models.BooleanField(default=True, help_text='Allow users to register for events')),
                ('program_registration_enabled', models.BooleanField(default=True, help_text='Allow users to register for programs')),
                ('auto_publish_student_projects', models.BooleanField(default=True, help_text='Auto-publish student-submitted projects')),
                ('search_results_per_category', models.PositiveIntegerField(default=5, help_text='Max results per category in global search')),
                ('banner_text', models.CharField(blank=True, max_length=500)),
                ('banner_link', models.URLField(blank=True, help_text='Optional link when banner is clicked')),
                ('banner_bg_color', models.CharField(default='#00D4FF', help_text='Hex color, e.g. #00D4FF', max_length=7)),
                ('banner_text_color', models.CharField(default='#000000', max_length=7)),
                ('banner_is_active', models.BooleanField(default=False)),
                ('carousel_slides', models.JSONField(blank=True, default=list)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
        migrations.RunPython(migrate_to_site_config, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='CarouselSlide',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='GeneralFAQ',
        ),
        migrations.DeleteModel(
            name='PlatformSettings',
        ),
        migrations.DeleteModel(
            name='SiteBanner',
        ),
    ]
