# Generated by Django 5.2.12 on 2026-04-11 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=100)),
                ('achievement_type', models.CharField(choices=[('placed', 'Placed'), ('promoted', 'Promoted'), ('freelancing', 'Freelancing'), ('project_launched', 'Project Launched')], max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('package_range', models.CharField(blank=True, max_length=50)),
                ('achieved_at', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course')),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
