# Generated by Django 5.2.15 on 2026-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studentoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('intern_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=150)),
                ('certificate_type', models.CharField(default='Certification Of Internship', max_length=100)),
                ('title', models.CharField(help_text='e.g. SQL AI SPARK Team Fellow', max_length=200)),
                ('description', models.TextField()),
                ('worked_tools', models.CharField(help_text='Comma-separated tools, e.g., Google Ads, Google Analytics', max_length=255)),
                ('badge_text', models.CharField(default='EXCELLENCE of SPARK', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
