# Generated by Django 5.2.15 on 2026-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Delivered', max_length=50)),
                ('attachments', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
    ]
