# Generated by Django 5.2.15 on 2026-06-22 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_emaillog'),
        ('showcase', '0002_alter_studentproject_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('skill', 'Skill'), ('tech', 'Technology'), ('tool', 'Tool'), ('general', 'General')], db_index=True, default='skill', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='worked_tools_text',
            field=models.CharField(blank=True, help_text='Comma-separated tools, e.g., Google Ads, Google Analytics', max_length=255),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='worked_tools',
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='worked_tools',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='courses.tag'),
        ),
    ]
