# Generated by Django 5.2.15 on 2026-06-22 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_data_phase4(apps, schema_editor):
    GeneralFAQ = apps.get_model('common', 'GeneralFAQ')
    CourseFAQ = apps.get_model('courses', 'CourseFAQ')
    FAQ = apps.get_model('courses', 'FAQ')

    CourseReview = apps.get_model('courses', 'CourseReview')
    Testimonial = apps.get_model('courses', 'Testimonial')
    Feedback = apps.get_model('courses', 'Feedback')

    AlumniProfile = apps.get_model('showcase', 'AlumniProfile')
    StudentOutcome = apps.get_model('courses', 'StudentOutcome')

    # 1. Migrate FAQs
    for f in GeneralFAQ.objects.all():
        FAQ.objects.create(
            course=None,
            question=f.question,
            answer=f.answer,
            order=f.order,
            is_active=f.is_active
        )

    for f in CourseFAQ.objects.all():
        FAQ.objects.create(
            course=f.course,
            question=f.question,
            answer=f.answer,
            order=f.order,
            is_active=True
        )

    # 2. Migrate Reviews & Testimonials to Feedback
    for r in CourseReview.objects.all():
        Feedback.objects.create(
            student=r.student,
            course=r.course,
            rating=r.rating,
            text=r.text,
            is_approved=True
        )

    for t in Testimonial.objects.all():
        Feedback.objects.create(
            student=None,
            course=None,
            name=t.name,
            role=t.role,
            image=t.image,
            rating=t.rating,
            text=t.text,
            is_approved=True
        )

    # 3. Migrate AlumniProfile to StudentOutcome
    for a in AlumniProfile.objects.all():
        StudentOutcome.objects.create(
            user=None,
            student_name=a.name,
            avatar=a.avatar,
            achievement_type="placed",
            company_name=a.current_company,
            role=a.current_role,
            package_range=a.package_range,
            course=a.course,
            achieved_at=None,
            batch_year=a.batch_year,
            linkedin_url=a.linkedin_url,
            short_quote=a.short_quote,
            is_featured=a.is_featured,
            is_published=a.is_published
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag_delete_skill_certificate_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0005_galleryimage_generalfaq'),
        ('showcase', '0003_alter_studentproject_tech_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='studentoutcome',
            options={'ordering': ['-batch_year', '-achieved_at', 'student_name']},
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='alumni/avatars/'),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='batch_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='short_quote',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='achieved_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='achievement_type',
            field=models.CharField(choices=[('placed', 'Placed'), ('promoted', 'Promoted'), ('freelancing', 'Freelancing'), ('project_launched', 'Project Launched')], default='placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='student_name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(migrate_data_phase4, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='CourseFAQ',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('student__isnull', False)), fields=('student', 'course'), name='unique_student_course_feedback'),
        ),
    ]
