# Generated by Django 5.2.15 on 2026-06-22 17:47

from django.db import migrations, models


def migrate_programs_and_curriculum(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Module = apps.get_model('courses', 'Module')
    Topic = apps.get_model('courses', 'Topic')
    Program = apps.get_model('programs', 'Program')
    StudentRegistration = apps.get_model('signin', 'StudentRegistration')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Media = apps.get_model('common', 'Media')

    # 1. Compile Module and Topic records into curriculum JSONField for each Course
    for course in Course.objects.all():
        curr_list = []
        for module in Module.objects.filter(course=course).order_by('order'):
            topics_list = []
            for topic in Topic.objects.filter(module=module).order_by('order'):
                topics_list.append({
                    "id": topic.id,
                    "title": topic.title,
                    "description": topic.description,
                    "order": topic.order
                })
            curr_list.append({
                "id": module.id,
                "title": module.title,
                "description": module.description,
                "order": module.order,
                "topics": topics_list
            })
        course.curriculum = curr_list
        course.save()

    # 2. Migrate Program records into Course records with course_type="fellowship" / "internship"
    User = apps.get_model('accounts', 'User')
    default_instructor = User.objects.filter(role='instructor').first() or User.objects.filter(is_superuser=True).first()
    if not default_instructor:
        default_instructor = User.objects.first()

    for p in Program.objects.all():
        c = Course.objects.create(
            instructor=default_instructor,
            name=p.title,
            slug=p.slug,
            description=p.description,
            image=p.image,
            banner=p.banner,
            level="beginner",
            prior_knowledge="",
            duration=p.duration,
            price=0,
            discount=0,
            is_trending=p.is_featured,
            is_published=p.is_published,
            course_type=p.program_type,
            curriculum=[],
            stipend=p.stipend,
            location=p.location,
            is_remote=p.is_remote,
            eligibility_criteria=p.eligibility_criteria,
            min_degree_level=p.min_degree_level,
            eligible_branches=p.eligible_branches,
            application_deadline=p.application_deadline,
            start_date=p.start_date,
            end_date=p.end_date,
            capacity=p.capacity,
            is_featured=p.is_featured
        )
        # Update StudentRegistration
        StudentRegistration.objects.filter(program=p).update(course=c)

    # 3. Re-point media attachments from Program to Course
    program_ct = ContentType.objects.filter(app_label='programs', model='program').first()
    course_ct = ContentType.objects.filter(app_label='courses', model='course').first()
    if program_ct and course_ct:
        for p in Program.objects.all():
            c = Course.objects.filter(slug=p.slug, course_type=p.program_type).first()
            if c:
                Media.objects.filter(content_type=program_ct, object_id=p.id).update(
                    content_type=course_ct,
                    object_id=c.id
                )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_coursereview_unique_together_and_more'),
        ('programs', '0001_initial'),
        ('signin', '0008_remove_studentregistration_email_and_more'),
        ('common', '0002_media'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('course', 'Course'), ('fellowship', 'Fellowship'), ('internship', 'Internship')], db_index=True, default='course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='eligibility_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eligible_branches',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='min_degree_level',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='stipend',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(migrate_programs_and_curriculum, reverse_code=migrations.RunPython.noop),
    ]
