# Generated by Django 5.2.15 on 2026-06-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_application_deadline_course_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
