from django.db import connection

sql = """
CREATE TABLE "signin_payment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "amount" numeric(10, 2) NOT NULL, "upi_transaction_id" varchar(100) NOT NULL UNIQUE, "status" varchar(20) NOT NULL, "remarks" text NOT NULL, "payment_date" timestamp with time zone NOT NULL, "student_registration_id" bigint NOT NULL);
ALTER TABLE "signin_payment" ADD CONSTRAINT "signin_payment_student_registration_b734fd0a_fk_signin_st" FOREIGN KEY ("student_registration_id") REFERENCES "signin_studentregistration" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "signin_payment_upi_transaction_id_fd4c6e10_like" ON "signin_payment" ("upi_transaction_id" varchar_pattern_ops);
CREATE INDEX "signin_payment_student_registration_id_b734fd0a" ON "signin_payment" ("student_registration_id");
"""

with connection.cursor() as cursor:
    cursor.execute(sql)
print("Table created successfully")
