# Generated by Django 5.2.12 on 2026-04-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_studentoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='alumni/avatars/')),
                ('batch_year', models.PositiveIntegerField()),
                ('current_company', models.CharField(max_length=100)),
                ('current_role', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('short_quote', models.CharField(blank=True, max_length=300)),
                ('package_range', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='courses.course')),
            ],
            options={
                'ordering': ['-batch_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/')),
                ('student_name', models.CharField(max_length=100)),
                ('batch_year', models.PositiveIntegerField()),
                ('demo_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='courses.course')),
                ('tech_tags', models.ManyToManyField(blank=True, to='courses.skill')),
            ],
            options={
                'ordering': ['-batch_year', 'title'],
            },
        ),
    ]
