# Generated by Django 5.2.12 on 2026-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='projects/thumbnails/'),
        ),
    ]
