# Generated by Django 5.2.15 on 2026-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag_delete_skill_certificate_course_and_more'),
        ('showcase', '0002_alter_studentproject_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='tech_tags',
            field=models.ManyToManyField(blank=True, to='courses.tag'),
        ),
    ]
