# Generated by Django 5.2.15 on 2026-06-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_studentproject_tech_tags'),
        ('courses', '0008_alter_coursereview_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniProfile',
        ),
    ]
