# Generated by Django 5.2.12 on 2026-04-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('hackathon', 'Hackathon'), ('meetup', 'Meetup')], db_index=True, max_length=20),
        ),
    ]
