# Generated by Django 5.2.12 on 2026-04-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(blank=True, help_text='Short plain-text description for cards', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Full description, supports Markdown'),
        ),
    ]
