# Generated by Django 5.2.15 on 2026-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactform',
            name='college',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactform',
            name='course_interested',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactform',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='form_type',
            field=models.CharField(choices=[('contact', 'Contact Inquiry'), ('lead', 'Course Interest Lead'), ('support', 'Support Request')], db_index=True, default='contact', max_length=20),
        ),
        migrations.AddField(
            model_name='contactform',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactform',
            name='passed_out_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contactform',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
