# Generated by Django 5.2.15 on 2026-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag_delete_skill_certificate_course_and_more'),
        ('portfolio', '0002_casestudy_created_at_casestudy_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='tech_tags',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='courses.tag'),
        ),
    ]
