# Generated by Django 5.2.15 on 2026-06-22 14:03

from django.db import migrations


def migrate_screenshots(apps, schema_editor):
    Screenshot = apps.get_model('portfolio', 'Screenshot')
    CaseStudy = apps.get_model('portfolio', 'CaseStudy')
    Media = apps.get_model('common', 'Media')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    case_study_ct = ContentType.objects.get_for_model(CaseStudy)

    for screenshot in Screenshot.objects.all():
        Media.objects.create(
            content_type=case_study_ct,
            object_id=screenshot.case_study_id,  # use case_study_id directly to avoid extra DB query
            image=screenshot.image,
            caption=screenshot.caption,
            order=screenshot.order
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_casestudy_tech_tags'),
        ('common', '0002_media'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(migrate_screenshots, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='screenshot',
            name='case_study',
        ),
        migrations.DeleteModel(
            name='TechTag',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
