# Generated by Django 5.2.12 on 2026-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Supports Markdown')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/images/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='programs/banners/')),
                ('program_type', models.CharField(choices=[('fellowship', 'Fellowship'), ('internship', 'Internship')], db_index=True, max_length=20)),
                ('duration', models.CharField(help_text="e.g. '3 months', '6 weeks'", max_length=50)),
                ('stipend', models.CharField(blank=True, help_text="e.g. '₹15,000/month'", max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('eligibility_criteria', models.TextField(help_text='Markdown description of eligibility')),
                ('min_degree_level', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('eligible_branches', models.TextField(blank=True, help_text='Comma-separated branch names')),
                ('application_deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-is_featured', 'application_deadline'],
            },
        ),
    ]
