# Generated by Django 5.2.15 on 2026-06-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_topic_module_delete_module_delete_topic'),
        ('programs', '0001_initial'),
        ('signin', '0009_remove_studentregistration_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
