# Generated by Django 5.2.15 on 2026-06-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_delete_program_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
    ]
