# Generated by Django 5.2.7 on 2025-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinprofile',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='course_interested',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='passed_out_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='specific_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signinprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
