# Generated by Django 5.2.7 on 2025-10-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_signinprofile_agreed_to_terms_signinprofile_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinprofile',
            name='percentage',
        ),
    ]
