# Generated by Django 5.2.7 on 2025-10-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_remove_signinprofile_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinprofile',
            name='education',
        ),
    ]
