# Generated by Django 5.2.12 on 2026-04-05 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('signin', '0004_remove_signinprofile_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street_address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('college', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('degree_level', models.CharField(choices=[('diploma', 'Diploma'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('graduation_year', models.PositiveIntegerField()),
                ('current_year', models.CharField(blank=True, max_length=20)),
                ('employment_status', models.CharField(choices=[('student', 'Student'), ('employed', 'Employed'), ('freelancer', 'Freelancer'), ('unemployed', 'Unemployed')], max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('interest_category', models.CharField(choices=[('fellowship', 'Fellowship'), ('internship', 'Internship'), ('workshop', 'Workshop'), ('course', 'Course'), ('other', 'Other')], max_length=20)),
                ('specific_interests', models.TextField(blank=True)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_profiles', to='programs.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
