# Generated by Django 5.2.15 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_registrationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=150)),
                ('current_year', models.CharField(max_length=50)),
                ('course_selected', models.CharField(max_length=150)),
                ('batch_type', models.CharField(max_length=50)),
                ('joining_date', models.CharField(max_length=20)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_transaction_id', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='registration_photos/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
