# Generated by Django 5.2.15 on 2026-06-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_studentregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigninProfile',
        ),
    ]
