# Generated by Django 5.2.15 on 2026-06-22 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_registration_profiles(apps, schema_editor):
    RegistrationProfile = apps.get_model('signin', 'RegistrationProfile')
    StudentRegistration = apps.get_model('signin', 'StudentRegistration')
    
    for rp in RegistrationProfile.objects.all():
        years = 0
        if rp.years_of_experience and str(rp.years_of_experience).isdigit():
            years = int(rp.years_of_experience)
            
        sr, created = StudentRegistration.objects.get_or_create(
            user=rp.user,
            defaults={
                'street_address': rp.street_address,
                'city': rp.city,
                'state': rp.state,
                'country': rp.country,
                'pincode': rp.pincode,
                'college_name': rp.college,
                'branch': rp.branch,
                'degree_level': rp.degree_level,
                'graduation_year': rp.graduation_year,
                'current_year': rp.current_year,
                'employment_status': rp.employment_status,
                'years_of_experience': years,
                'course_selected': rp.interest_category,
                'program': rp.program,
                'terms_agreed': rp.terms_agreed,
                'total_fee': 0.0,
                'paid_fee': 0.0,
                'balance_fee': 0.0,
                'status': 'Active',
            }
        )
        if not created:
            sr.street_address = rp.street_address
            sr.city = rp.city
            sr.state = rp.state
            sr.country = rp.country
            sr.pincode = rp.pincode
            sr.college_name = rp.college
            sr.branch = rp.branch
            sr.degree_level = rp.degree_level
            sr.graduation_year = rp.graduation_year
            sr.current_year = rp.current_year
            sr.employment_status = rp.employment_status
            sr.years_of_experience = years
            sr.course_selected = rp.interest_category
            sr.program = rp.program
            sr.terms_agreed = rp.terms_agreed
            sr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag_delete_skill_certificate_course_and_more'),
        ('programs', '0001_initial'),
        ('signin', '0007_delete_signinprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='phone',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registrations', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='degree_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registrations', to='programs.program'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='street_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='balance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='batch_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='course_selected',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='current_year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='dob',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='joining_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='upi_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('student_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='signin.studentregistration')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.RunPython(
            migrate_registration_profiles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='RegistrationProfile',
        ),
    ]
