# Generated by Django 5.2.15 on 2026-06-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0008_remove_studentregistration_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='program',
        ),
    ]
