# Generated by Django 5.2.15 on 2026-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0009_remove_studentregistration_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='why_join',
            field=models.TextField(blank=True, help_text='Why do you want to join Algonex?'),
        ),
    ]
